<h3><?= Yii::t('app', 'Главная') ?></h3>

<?= $this->chunk('alerts') ?>

<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu finibus mauris. Nulla vel varius urna. Nam bibendum eu nulla nec dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dui ante, ultricies eget dolor vitae, blandit suscipit quam. Duis dui lorem, congue id tristique in, scelerisque sed est. Ut in viverra purus. Sed quis volutpat lorem.

    Vestibulum non mollis velit, sed tincidunt dolor. Suspendisse accumsan volutpat diam eu finibus. Pellentesque sit amet quam a felis maximus fringilla. Mauris nibh dui, aliquam eu felis nec, tincidunt dapibus lacus. Praesent id massa felis. Aliquam ut consectetur justo. Nunc ex est, molestie at metus a, tristique imperdiet ex. Quisque dignissim, augue non venenatis bibendum, enim ex convallis nisi, consectetur fermentum ligula nisl sed velit. Ut egestas tellus vitae gravida iaculis. Donec vitae posuere eros. Proin nec felis quis tellus eleifend volutpat sed ac lectus. Nullam molestie enim eget felis maximus, sed porttitor neque ultricies. Integer luctus malesuada lectus, eu blandit dolor finibus ac.

    Praesent et diam eu est tempor vulputate. Suspendisse eget magna elementum, gravida urna a, rhoncus velit. Donec sollicitudin a metus sit amet elementum. Nam magna nulla, blandit eget risus et, malesuada pellentesque diam. Nulla efficitur, urna at vestibulum luctus, odio neque ultrices ligula, non fermentum diam dolor at justo. Cras in quam id magna sollicitudin egestas. Sed blandit tortor sit amet luctus hendrerit. Cras laoreet tincidunt facilisis. Suspendisse potenti. Proin tempus nunc in risus consequat vehicula. Nullam nisi arcu, mollis at tortor a, congue eleifend justo. Cras ornare risus vel neque sollicitudin, in volutpat lacus feugiat.

    Maecenas accumsan, tortor porta vulputate vulputate, justo libero faucibus elit, ac euismod nisl sapien quis ex. Ut enim orci, ultricies id lobortis fermentum, efficitur vitae libero. Fusce condimentum eu velit et vestibulum. Aliquam malesuada eu diam nec vehicula. Nam vitae sem ut nisl molestie hendrerit. Suspendisse non viverra orci, sit amet ultricies tortor. Morbi consequat scelerisque nunc, at cursus sem commodo id.

    Curabitur risus lectus, porta in nisi sit amet, hendrerit tincidunt quam. Donec tincidunt consequat lacus, a scelerisque augue porta eu. Curabitur tempus tellus id justo hendrerit, suscipit mattis leo egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque pretium suscipit consectetur. Nulla viverra quam eu nisi aliquet placerat. Donec volutpat dui at purus suscipit pulvinar. Quisque congue interdum cursus. Ut quis felis id lorem rhoncus lobortis. Suspendisse venenatis ante orci, vitae finibus metus venenatis cursus. Vivamus at ullamcorper nulla. Morbi eleifend massa in semper iaculis. Integer porttitor, dui id ultrices imperdiet, justo nisi rutrum lectus, sed malesuada velit nunc nec ipsum. Sed dignissim justo in rutrum tempor. Suspendisse ornare mi nec odio lobortis mattis. Morbi nec dignissim risus, in luctus magna.
</p>

<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu finibus mauris. Nulla vel varius urna. Nam bibendum eu nulla nec dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dui ante, ultricies eget dolor vitae, blandit suscipit quam. Duis dui lorem, congue id tristique in, scelerisque sed est. Ut in viverra purus. Sed quis volutpat lorem.

    Vestibulum non mollis velit, sed tincidunt dolor. Suspendisse accumsan volutpat diam eu finibus. Pellentesque sit amet quam a felis maximus fringilla. Mauris nibh dui, aliquam eu felis nec, tincidunt dapibus lacus. Praesent id massa felis. Aliquam ut consectetur justo. Nunc ex est, molestie at metus a, tristique imperdiet ex. Quisque dignissim, augue non venenatis bibendum, enim ex convallis nisi, consectetur fermentum ligula nisl sed velit. Ut egestas tellus vitae gravida iaculis. Donec vitae posuere eros. Proin nec felis quis tellus eleifend volutpat sed ac lectus. Nullam molestie enim eget felis maximus, sed porttitor neque ultricies. Integer luctus malesuada lectus, eu blandit dolor finibus ac.

    Praesent et diam eu est tempor vulputate. Suspendisse eget magna elementum, gravida urna a, rhoncus velit. Donec sollicitudin a metus sit amet elementum. Nam magna nulla, blandit eget risus et, malesuada pellentesque diam. Nulla efficitur, urna at vestibulum luctus, odio neque ultrices ligula, non fermentum diam dolor at justo. Cras in quam id magna sollicitudin egestas. Sed blandit tortor sit amet luctus hendrerit. Cras laoreet tincidunt facilisis. Suspendisse potenti. Proin tempus nunc in risus consequat vehicula. Nullam nisi arcu, mollis at tortor a, congue eleifend justo. Cras ornare risus vel neque sollicitudin, in volutpat lacus feugiat.

    Maecenas accumsan, tortor porta vulputate vulputate, justo libero faucibus elit, ac euismod nisl sapien quis ex. Ut enim orci, ultricies id lobortis fermentum, efficitur vitae libero. Fusce condimentum eu velit et vestibulum. Aliquam malesuada eu diam nec vehicula. Nam vitae sem ut nisl molestie hendrerit. Suspendisse non viverra orci, sit amet ultricies tortor. Morbi consequat scelerisque nunc, at cursus sem commodo id.

    Curabitur risus lectus, porta in nisi sit amet, hendrerit tincidunt quam. Donec tincidunt consequat lacus, a scelerisque augue porta eu. Curabitur tempus tellus id justo hendrerit, suscipit mattis leo egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque pretium suscipit consectetur. Nulla viverra quam eu nisi aliquet placerat. Donec volutpat dui at purus suscipit pulvinar. Quisque congue interdum cursus. Ut quis felis id lorem rhoncus lobortis. Suspendisse venenatis ante orci, vitae finibus metus venenatis cursus. Vivamus at ullamcorper nulla. Morbi eleifend massa in semper iaculis. Integer porttitor, dui id ultrices imperdiet, justo nisi rutrum lectus, sed malesuada velit nunc nec ipsum. Sed dignissim justo in rutrum tempor. Suspendisse ornare mi nec odio lobortis mattis. Morbi nec dignissim risus, in luctus magna.
</p>

<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu finibus mauris. Nulla vel varius urna. Nam bibendum eu nulla nec dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dui ante, ultricies eget dolor vitae, blandit suscipit quam. Duis dui lorem, congue id tristique in, scelerisque sed est. Ut in viverra purus. Sed quis volutpat lorem.

    Vestibulum non mollis velit, sed tincidunt dolor. Suspendisse accumsan volutpat diam eu finibus. Pellentesque sit amet quam a felis maximus fringilla. Mauris nibh dui, aliquam eu felis nec, tincidunt dapibus lacus. Praesent id massa felis. Aliquam ut consectetur justo. Nunc ex est, molestie at metus a, tristique imperdiet ex. Quisque dignissim, augue non venenatis bibendum, enim ex convallis nisi, consectetur fermentum ligula nisl sed velit. Ut egestas tellus vitae gravida iaculis. Donec vitae posuere eros. Proin nec felis quis tellus eleifend volutpat sed ac lectus. Nullam molestie enim eget felis maximus, sed porttitor neque ultricies. Integer luctus malesuada lectus, eu blandit dolor finibus ac.

    Praesent et diam eu est tempor vulputate. Suspendisse eget magna elementum, gravida urna a, rhoncus velit. Donec sollicitudin a metus sit amet elementum. Nam magna nulla, blandit eget risus et, malesuada pellentesque diam. Nulla efficitur, urna at vestibulum luctus, odio neque ultrices ligula, non fermentum diam dolor at justo. Cras in quam id magna sollicitudin egestas. Sed blandit tortor sit amet luctus hendrerit. Cras laoreet tincidunt facilisis. Suspendisse potenti. Proin tempus nunc in risus consequat vehicula. Nullam nisi arcu, mollis at tortor a, congue eleifend justo. Cras ornare risus vel neque sollicitudin, in volutpat lacus feugiat.

    Maecenas accumsan, tortor porta vulputate vulputate, justo libero faucibus elit, ac euismod nisl sapien quis ex. Ut enim orci, ultricies id lobortis fermentum, efficitur vitae libero. Fusce condimentum eu velit et vestibulum. Aliquam malesuada eu diam nec vehicula. Nam vitae sem ut nisl molestie hendrerit. Suspendisse non viverra orci, sit amet ultricies tortor. Morbi consequat scelerisque nunc, at cursus sem commodo id.

    Curabitur risus lectus, porta in nisi sit amet, hendrerit tincidunt quam. Donec tincidunt consequat lacus, a scelerisque augue porta eu. Curabitur tempus tellus id justo hendrerit, suscipit mattis leo egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque pretium suscipit consectetur. Nulla viverra quam eu nisi aliquet placerat. Donec volutpat dui at purus suscipit pulvinar. Quisque congue interdum cursus. Ut quis felis id lorem rhoncus lobortis. Suspendisse venenatis ante orci, vitae finibus metus venenatis cursus. Vivamus at ullamcorper nulla. Morbi eleifend massa in semper iaculis. Integer porttitor, dui id ultrices imperdiet, justo nisi rutrum lectus, sed malesuada velit nunc nec ipsum. Sed dignissim justo in rutrum tempor. Suspendisse ornare mi nec odio lobortis mattis. Morbi nec dignissim risus, in luctus magna.
</p>

<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu finibus mauris. Nulla vel varius urna. Nam bibendum eu nulla nec dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dui ante, ultricies eget dolor vitae, blandit suscipit quam. Duis dui lorem, congue id tristique in, scelerisque sed est. Ut in viverra purus. Sed quis volutpat lorem.

    Vestibulum non mollis velit, sed tincidunt dolor. Suspendisse accumsan volutpat diam eu finibus. Pellentesque sit amet quam a felis maximus fringilla. Mauris nibh dui, aliquam eu felis nec, tincidunt dapibus lacus. Praesent id massa felis. Aliquam ut consectetur justo. Nunc ex est, molestie at metus a, tristique imperdiet ex. Quisque dignissim, augue non venenatis bibendum, enim ex convallis nisi, consectetur fermentum ligula nisl sed velit. Ut egestas tellus vitae gravida iaculis. Donec vitae posuere eros. Proin nec felis quis tellus eleifend volutpat sed ac lectus. Nullam molestie enim eget felis maximus, sed porttitor neque ultricies. Integer luctus malesuada lectus, eu blandit dolor finibus ac.

    Praesent et diam eu est tempor vulputate. Suspendisse eget magna elementum, gravida urna a, rhoncus velit. Donec sollicitudin a metus sit amet elementum. Nam magna nulla, blandit eget risus et, malesuada pellentesque diam. Nulla efficitur, urna at vestibulum luctus, odio neque ultrices ligula, non fermentum diam dolor at justo. Cras in quam id magna sollicitudin egestas. Sed blandit tortor sit amet luctus hendrerit. Cras laoreet tincidunt facilisis. Suspendisse potenti. Proin tempus nunc in risus consequat vehicula. Nullam nisi arcu, mollis at tortor a, congue eleifend justo. Cras ornare risus vel neque sollicitudin, in volutpat lacus feugiat.

    Maecenas accumsan, tortor porta vulputate vulputate, justo libero faucibus elit, ac euismod nisl sapien quis ex. Ut enim orci, ultricies id lobortis fermentum, efficitur vitae libero. Fusce condimentum eu velit et vestibulum. Aliquam malesuada eu diam nec vehicula. Nam vitae sem ut nisl molestie hendrerit. Suspendisse non viverra orci, sit amet ultricies tortor. Morbi consequat scelerisque nunc, at cursus sem commodo id.

    Curabitur risus lectus, porta in nisi sit amet, hendrerit tincidunt quam. Donec tincidunt consequat lacus, a scelerisque augue porta eu. Curabitur tempus tellus id justo hendrerit, suscipit mattis leo egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque pretium suscipit consectetur. Nulla viverra quam eu nisi aliquet placerat. Donec volutpat dui at purus suscipit pulvinar. Quisque congue interdum cursus. Ut quis felis id lorem rhoncus lobortis. Suspendisse venenatis ante orci, vitae finibus metus venenatis cursus. Vivamus at ullamcorper nulla. Morbi eleifend massa in semper iaculis. Integer porttitor, dui id ultrices imperdiet, justo nisi rutrum lectus, sed malesuada velit nunc nec ipsum. Sed dignissim justo in rutrum tempor. Suspendisse ornare mi nec odio lobortis mattis. Morbi nec dignissim risus, in luctus magna.
</p>

<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu finibus mauris. Nulla vel varius urna. Nam bibendum eu nulla nec dignissim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dui ante, ultricies eget dolor vitae, blandit suscipit quam. Duis dui lorem, congue id tristique in, scelerisque sed est. Ut in viverra purus. Sed quis volutpat lorem.

    Vestibulum non mollis velit, sed tincidunt dolor. Suspendisse accumsan volutpat diam eu finibus. Pellentesque sit amet quam a felis maximus fringilla. Mauris nibh dui, aliquam eu felis nec, tincidunt dapibus lacus. Praesent id massa felis. Aliquam ut consectetur justo. Nunc ex est, molestie at metus a, tristique imperdiet ex. Quisque dignissim, augue non venenatis bibendum, enim ex convallis nisi, consectetur fermentum ligula nisl sed velit. Ut egestas tellus vitae gravida iaculis. Donec vitae posuere eros. Proin nec felis quis tellus eleifend volutpat sed ac lectus. Nullam molestie enim eget felis maximus, sed porttitor neque ultricies. Integer luctus malesuada lectus, eu blandit dolor finibus ac.

    Praesent et diam eu est tempor vulputate. Suspendisse eget magna elementum, gravida urna a, rhoncus velit. Donec sollicitudin a metus sit amet elementum. Nam magna nulla, blandit eget risus et, malesuada pellentesque diam. Nulla efficitur, urna at vestibulum luctus, odio neque ultrices ligula, non fermentum diam dolor at justo. Cras in quam id magna sollicitudin egestas. Sed blandit tortor sit amet luctus hendrerit. Cras laoreet tincidunt facilisis. Suspendisse potenti. Proin tempus nunc in risus consequat vehicula. Nullam nisi arcu, mollis at tortor a, congue eleifend justo. Cras ornare risus vel neque sollicitudin, in volutpat lacus feugiat.

    Maecenas accumsan, tortor porta vulputate vulputate, justo libero faucibus elit, ac euismod nisl sapien quis ex. Ut enim orci, ultricies id lobortis fermentum, efficitur vitae libero. Fusce condimentum eu velit et vestibulum. Aliquam malesuada eu diam nec vehicula. Nam vitae sem ut nisl molestie hendrerit. Suspendisse non viverra orci, sit amet ultricies tortor. Morbi consequat scelerisque nunc, at cursus sem commodo id.

    Curabitur risus lectus, porta in nisi sit amet, hendrerit tincidunt quam. Donec tincidunt consequat lacus, a scelerisque augue porta eu. Curabitur tempus tellus id justo hendrerit, suscipit mattis leo egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque pretium suscipit consectetur. Nulla viverra quam eu nisi aliquet placerat. Donec volutpat dui at purus suscipit pulvinar. Quisque congue interdum cursus. Ut quis felis id lorem rhoncus lobortis. Suspendisse venenatis ante orci, vitae finibus metus venenatis cursus. Vivamus at ullamcorper nulla. Morbi eleifend massa in semper iaculis. Integer porttitor, dui id ultrices imperdiet, justo nisi rutrum lectus, sed malesuada velit nunc nec ipsum. Sed dignissim justo in rutrum tempor. Suspendisse ornare mi nec odio lobortis mattis. Morbi nec dignissim risus, in luctus magna.
</p>
